<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rips</string>
	</array>
	<key>name</key>
	<string>Rips</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Registers $1..$15</string>
			<key>match</key>
			<string>\$(([1]?[0-5])|[0-9])</string>
			<key>name</key>
			<string>variable.parameter.rips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Ports @1..@3</string>
			<key>match</key>
			<string>\@([0-3])</string>
			<key>name</key>
			<string>entity.name.function.rips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instructions provided by the Rips assembly language</string>
			<key>match</key>
			<string>\b(add|and|j|jal|ji|jr|beqz|bnez|lesr|li|move|nop|neg|not|or|sesm|sesr|sub)\b</string>
			<key>name</key>
			<string>support.function.source.rips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers like +12, -3, 55, 0x3F</string>
			<key>match</key>
			<string>\b((\-)?[0-9]*)\b</string>
			<key>name</key>
			<string>constant.numeric.rips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Labels at line start: begin_repeat: add ...</string>
			<key>match</key>
			<string>\b[\w]+\b:</string>
			<key>name</key>
			<string>entity.name.tag.rips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single line comments</string>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.rips</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.rips</string>
	<key>uuid</key>
	<string>f43b595a-700b-4f4f-a525-9c78c44d0254</string>
</dict>
</plist>
